version: '3.8'

services:
  nginx:
    image: pixelcrush/bracelet-nginx:0.7.3
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./certs/webroot:/webroot
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./conf/default.conf.prod.template:/etc/nginx/templates/default.conf.template
      - ./conf/cors.conf:/etc/nginx/cors.conf
      - ./conf/ssl-prod.template:/etc/nginx/templates/ssl-prod.template
      - ${CERTS_DIR}:/certs
    environment:
      HTTPS_PLATFORM_DOMAIN: ${HTTPS_PLATFORM_DOMAIN}
      SSL_CONF: ${SSL_CONF}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 15432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  api:
    image: pixelcrush/bracelet-api:0.5.0
    restart: unless-stopped
    environment:
      API_DB_URL: ${API_DB_URL}
      API_REDIS_URL: ${API_REDIS_URL}
      API_INFRASTRUCTURE_SFU_IP: ${API_INFRASTRUCTURE_SFU_IP}
      API_S3_ACCESS_KEY_ID: ${API_S3_ACCESS_KEY_ID}
      API_S3_SECRET_ACCESS_KEY: ${API_S3_SECRET_ACCESS_KEY}
      API_S3_REGION: ${API_S3_REGION}
      API_S3_ENDPOINT_URL: ${API_S3_ENDPOINT_URL}
      API_S3_BUCKET: ${API_S3_BUCKET}
      API_S3_ACL: ${API_S3_ACL}
      API_S3_TTL: ${API_S3_TTL}
      API_EMAIL_SMTP_HOSTNAME: ${API_EMAIL_SMTP_HOSTNAME}
      API_EMAIL_SMTP_PORT: ${API_EMAIL_SMTP_PORT}
      API_EMAIL_USER_ACCOUNT: ${API_EMAIL_USER_ACCOUNT}
      API_EMAIL_FROM_REAL_NAME: ${API_EMAIL_FROM_REAL_NAME}
      API_EMAIL_FROM_EMAIL: ${API_EMAIL_FROM_EMAIL}
      API_EMAIL_PASSWORD: ${API_EMAIL_PASSWORD}
      API_EMAIL_ENABLE_SSL: ${API_EMAIL_ENABLE_SSL}
      API_EMAIL_ENABLE_TLS: ${API_EMAIL_ENABLE_TLS}
      API_EMAIL_PREFIX_URL: ${API_EMAIL_PREFIX_URL}
      API_EMAIL_EDIT_PASSWORD_REDIRECT_URL: ${API_EMAIL_EDIT_PASSWORD_REDIRECT_URL}
      API_EMAIL_ACTIVATE_ACCOUNT_REDIRECT_URL: ${API_EMAIL_ACTIVATE_ACCOUNT_REDIRECT_URL}
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  redis:
    image: redis:6.2.4
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PW}" ]
    volumes:
      - redis-data:/data
    ports:
      - 16379:6379
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  postgres-data:
  redis-data:
